# This is a basic workflow to help you get started with Actions

name: First Workflows
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: | 
          echo "First output"
          echo "Second output"
